"""empty message

Revision ID: 1e0d5ce89f9d
Revises: 
Create Date: 2025-04-10 14:00:58.224036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0d5ce89f9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('guru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    op.drop_table('guru')
    op.drop_table('user')
    op.drop_table('kelas')
    # ### end Alembic commands ###
